WIP: Implement Iterator on ImmutableArray
codelicia/immutable pull request #7
Opened 2019-08-06 19:08 UTC by EHER

In order to have ImmutableArray as close as possible as a classic array Iterator should be implemented.

2019-08-20 08:42 UTC, airtonzanon approved these changes
LGTM

2019-08-22 14:48 UTC, malukenho requested changes

2019-08-22 14:48 UTC, malukenho commented on test/unit/ImmutableArrayTest.php
> +            $expectedArray[$key] = $value;
this is `$actual`, not `$expected`

2019-08-22 14:48 UTC, malukenho commented on test/unit/ImmutableArrayTest.php
> +        $immutableArray = new ImmutableArray(['a', 'b', 'c']);
```php
$expected = ['a', 'b', 'c'];
$immutableArray = new ImmutableArray($expected);

// ...

self::assertSame($actual, $expected);
```

2019-08-22 16:04 UTC, malukenho commented on src/ImmutableArray.php
> +        $this->position = 0;
you can do it on the initialization itself `private int $position = 0;`

2019-08-22 16:10 UTC, malukenho commented
As talked offline, it would be nice to have a test with `array_map` for example.

2019-10-16 13:30 UTC, malukenho approved these changes

2020-11-17 22:38 UTC, closed without merging